name: post-daily-paper

on:
  schedule:
    # ┌──────── ┬──────── ┬────────┬────────┬────────┐
    # │ minute  │ hour    │  day   │ month  │  dow   │
    # └──────── ┴──────── ┴────────┴────────┴────────┘
    # 0 */3 * * *  → 0 分ジャストに 3 時間おき（UTC）
    # 分，時，日，月，曜日
    - cron:  '0 1 * * *'

  workflow_dispatch:      # 手動トリガーも欲しい時用（GitHub UI から Run）

jobs:
  post-paper:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY:  ${{ secrets.OPENAI_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL:   ${{ secrets.SLACK_CHANNEL }}
      SS_API_KEY:      ${{ secrets.SS_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SlackBot script
        run: python recommend_bot.py
